### ISSUE TITLE
Doesn't seem to be working at all.

### ISSUE THREAD

**Issue by doZennn** [xiel/embla-carousel-wheel-gestures#132]
I've tried with both demos [here](https://github.com/xiel/embla-carousel-wheel-gestures#examples) on the latest versions of Firefox & Chrome. Nothing happens when scrolling with a mouse wheel.

**Comment by xiel** [comment]
Hey @doZennn 
its still working for me. What kind of mouse are you using? You need to use a mouse or trackpad that can scroll horizontally for these examples to work. It's tested on Microsoft Surface hardware and macOS with quite few devices.

**Comment by doZennn** [comment]
Oops, my bad. Looks like I misunderstood what this is for. I was under the impression this was for adding "scroll to slide" functionality which I'm having problems implementing in a clean way.
