### ISSUE TITLE
Scrolling Intensity

### ISSUE THREAD

**Issue by jonrrivera** [xiel/embla-carousel-wheel-gestures#141]
hey! Thanks so much for this awesome plug-in! you are really making lives easier

I was wondering if there is a way to make the scrolling at the beginning and end of the slider less `harsh`.
You could see this behavior in your [example](https://codesandbox.io/s/github/xiel/embla-carousel-wheel-gestures/tree/master/docs/react?file=/src/js/EmblaCarousel.tsx:879-942).

I tried using [inViewThreshold](https://www.embla-carousel.com/api/options/#containscroll), and [containScroll](https://www.embla-carousel.com/api/options/#containscroll) from Emba, but no luck. Here's the [example](https://forest-road.vercel.app/) I'm working on so can have a better idea of the smoother expected behavior. 

Would you have any suggestions? I'm happy to help. 

Thank you!

**Comment by Songkeys** [comment]
> Have you tried using native scroll snaps insread?

I can get it working while use it alone, but not sure how to use it with the embla carousel, do you have any advice? thank you!

**Comment by xiel** [comment]
@Songkeys They are not meant to be combined. But for full page scroller scroll snaps are likely the better option imho.
