### ISSUE TITLE
Convert to Plugin

### ISSUE THREAD

**Issue by xiel** [xiel/embla-carousel-wheel-gestures#144]
Embla has a [plugin system](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.0) now. 

Convert this to use the new **plugin API**.

**Comment by davidcetinkaya** [comment]
We also need to add it to the documentation website!

**Comment by davidcetinkaya** [comment]
We should also remember to add an example to the examples page on the documentation website 🙂.

My second child was born a week ago so I’m going to be pretty busy for a period of time 😅. @xiel, do you want me to add you to the embla-carousel CodeSandbox group?

Thank you for your awesome work on this package.

Cheers,
David

**Comment by xiel** [comment]
@davidcetinkaya Wow, congrats! Take your time 👼

I'll try to convert it into a plugin the next few days and use your Autoplay plugin as an implementation guide.
I will definitely notify you if I run into any problems, but please do not feel pressured to answer swiftly, there are more important things in life.

I have not worked with CodeSandbox Groups yet, do you have a link to it? If I can add examples there, sure add me 👍

**Comment by davidcetinkaya** [comment]
Thanks @xiel,
I've invited you to the team now. I used your GitHub profile email. Feel free to change and/or update other sandboxes if you want, I trust you 🙂.

**Comment by davidcetinkaya** [comment]
Hello again Felix (@xiel),

I've created a page for the Wheel Gesture plugin [here](https://www.embla-carousel.com/plugins/wheel-gestures/). Feel free to add content to it if you want 🙂. 

Cheers,
David

**Comment by xiel** [comment]
Awesome, the conversion to a proper plugin is released as version [v2.0.0](https://github.com/xiel/embla-carousel-wheel-gestures/releases/tag/v2.0.0). It was a pretty easy transformation and really cool that you only destroy & re-init when options change :)

I'll send you a PR for the page in the docs tomorrow evening.

Cheers,
Felix
