### ISSUE TITLE
Customize scroll axis

### ISSUE THREAD

**Issue by lukasIO** [xiel/embla-carousel-wheel-gestures#149]
Hi, 

thanks first of all for a very useful plugin!

I was wondering if you'd be open to add a way to customize the scrolling axis.
Example: 
Given a horizontal embla carousel, I'd want to slide on vertical scroll events instead of horizontal scroll events.

I imagine something like 
```ts
type WheelGesturesPluginOptions = {
  wheelDraggingClass: string,
  forceWheelAxis?: 'x' | 'y'  // defaults to undefined
}
```
and subsequently
```ts

    function handleWheel(state: WheelEventState) {
      const {
        axisDelta: [deltaX, deltaY],
      } = state
      const scrollAxis = foceWheelAxis ?? engine.options.axis;
      const primaryAxisDelta = scrollAxis === 'x' ? deltaX : deltaY
      const crossAxisDelta = scrollAxis === 'x' ? deltaY : deltaX
```

would be happy to submit a PR if you think that it'd be a fitting addition to your plugin.

**Comment by xiel** [comment]
Yes, I'm happy to take a PR to support this.

**Comment by davidcetinkaya** [comment]
@lukasIO, feel free to add this option to the [documentation website](https://www.embla-carousel.com/plugins/wheel-gestures/#options) too. I would be happy to approve your PR.

**Comment by davidcetinkaya** [comment]
@lukasIO I've added [this](https://github.com/xiel/embla-carousel-wheel-gestures/issues/149#issuecomment-989167196) to the documentation website so no PR needed.

**Comment by lukasIO** [comment]
thank you!
