### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by davidcetinkaya** [xiel/embla-carousel-wheel-gestures#155]
Hi @xiel,

I hope you're doing great. I just released Embla [v.6.2.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.2.0) with the **global options feature**. Users can now set global options that will be applied to all their plugin instances as [described here](https://www.embla-carousel.com/api/plugins/#options):

```js
import Autoplay from 'embla-carousel-autoplay'

Autoplay.globalOptions = { delay: 4000 }
``` 

This feature is by no means mandatory for plugins, but feel free to implement it if you want. Thank you for your time!

Cheers,
David

**Comment by xiel** [comment]
Good idea! Will add this soon, it's a quick win :)

**Comment by xiel** [comment]
Release this feature https://github.com/xiel/embla-carousel-wheel-gestures/releases/tag/v2.1.0 🚀

Thanks for opening the issue!

**Comment by davidcetinkaya** [comment]
Awesome @xiel, thank you 😊!
