### ISSUE TITLE
Support use in Shadow DOM

### ISSUE THREAD

**Issue by careless-esper** [xiel/embla-carousel-wheel-gestures#159]
### Bug Description
This plugin does not function properly when using with an instance of Embla Carousel contained in a Shadow DOM. 

### CodeSandbox
https://codesandbox.io/s/sleepy-wing-e8or8g

### Steps to reproduce
1. Open https://codesandbox.io/s/sleepy-wing-e8or8g
2. Use mouse wheel to scroll through top carousel—carousel scrolls as expected
3. Attempt to use mouse wheel to scroll through bottom carousel—carousel does not scroll properly

### Suggested Fix
1. In the [createRelativeMouseEvent](https://github.com/xiel/embla-carousel-wheel-gestures/blob/master/embla-carousel-wheel-gestures/src/WheelGesturesPlugin.ts#L94) function, when creating the MouseEvent, add `composed: true` to the dictionary parameter (See https://developer.mozilla.org/en-US/docs/Web/API/Event/composed).

**Comment by xiel** [comment]
Thanks for opening the issue, providing a repro and suggesting even a fix. 🤟

I'll try to get this fix in later today/tomorrow.

**Comment by xiel** [comment]
@careless-esper Thanks again, for the perfect issue & repro.

I even stole your repro and added it to the [demos](https://embla-carousel-wheel-gestures.xiel.dev/shadow.html), hope that's OK 😬

The fix is now available in newly published `v2.1.1`
