### ISSUE TITLE
Target option

### ISSUE THREAD

**Issue by vitaly-phntm** [xiel/embla-carousel-wheel-gestures#165]
Would be great if you can pass target option. Use case if there is one carousel on the non scrollable page and I want it to scroll on document.documentElement instead of carousel element

**Comment by xiel** [comment]
Yes, we can consider this an option. But I wonder, could you not achieve the same by making the carousel larger/cover the whole screen, and instead the content using padding/max-heights if needed?

**Comment by vitaly-phntm** [comment]
There are other interactive elements on the page and carousel sandwiched in between them with flexbox, making it fixed in the layout will make it a lot harder to build the layout with some additional js involved in scaling. Would be a lot easier to just add a target option (which is what I'm doing atm). Would be nicer if I didn't have to modify the code of the library :)

**Comment by xiel** [comment]
Thanks for the explanation, sounds reasonable, I'll have a look at it.
