### ISSUE TITLE
Support for embla-carousel v8

### ISSUE THREAD

**Issue by tobimori** [xiel/embla-carousel-wheel-gestures#179]
The plugin fails to initialize a carousel with the newest release candidate of embla-carousel, due to optionsHandler now being passed to the init function.

Changes need to be made similar to here: https://github.com/davidjerleke/embla-carousel/commit/f3fc83286fc7f9245b4ca2ea896812958e934ee0

I can provide a PR if needed.

**Comment by jirbjirbjirb** [comment]
would also love to see this enabled for v8. this issue is currently blocking me from updating our carousels and benefitting from v8 bugfixes

**Comment by xiel** [comment]
@tobimori PR would be welcome, otherwise I’ll try to fix this soon as well.

**Comment by tobimori** [comment]
> @tobimori PR would be welcome, otherwise I’ll try to fix this soon as well. 

Gonna do it tomorrow

**Comment by xiel** [comment]
It's done: https://github.com/xiel/embla-carousel-wheel-gestures/releases/tag/v8.0.0-rc03

**Comment by smarlhens** [comment]
Hey there 👋🏻 ,

I hope you are well.

It seems that [`embla-carousel`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0) has reached stable v8, do you plan to release a stable release of you library supporting it ?

Thanks in advance 🙏🏻
