### ISSUE TITLE
Cannot install with NPM

### ISSUE THREAD

**Issue by 0t4u** [xiel/embla-carousel-wheel-gestures#182]
When installing with NPM, it complains that it cannot find the peer dependency embla-carousel@8.0.0 (it doesn't exist). NPM does not seem to recognise embla-carousel@8.0.0-rc3 as compatible with 8.0.0. 

Here is the full output:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: embla-carousel-wheel-gestures@8.0.0-rc03        
npm WARN Found: embla-carousel@undefined
npm WARN node_modules/embla-carousel
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer embla-carousel@"^8.0.0" from embla-carousel-wheel-gestures@8.0.0-rc03
npm WARN node_modules/embla-carousel-wheel-gestures
npm WARN   embla-carousel-wheel-gestures@"*" from the root project        
npm ERR! code ETARGET
npm ERR! notarget No matching version found for embla-carousel@^8.0.0.    
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

To reproduce this error, run `npm install embla-carousel-react`, then `npm install embla-carousel-react`, and the error would be shown in the terminal.

**Comment by xiel** [comment]
@0t4u Hi, thanks for the issue, I did not realize how picky npm would be with the peerDep. Please try again with the newest version.
