### ISSUE TITLE
NPM install dependency conflict

### ISSUE THREAD

**Issue by me-0xe** [xiel/embla-carousel-wheel-gestures#186]
Similar to this earlier issue [Cannot install with NPM #182](https://github.com/xiel/embla-carousel-wheel-gestures/issues/182)
There is a dependency conflict when installing via npm with the latest embla-carousel `8.0.0-rc7`.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: embla-carousel-wheel-gestures@8.0.0-rc04
npm ERR! Found: embla-carousel@8.0.0-rc07
npm ERR! node_modules/embla-carousel
```
**Suggestion**
It looks like the other plugins endorsed by the docs are tagging a release with the same `rc` as the main `embla-carousel` package. Maybe using the same approach when bumping the dependancy could help prevent future confusion for integrators?

![Screenshot 2023-07-17 at 11 35 06 AM](https://github.com/xiel/embla-carousel-wheel-gestures/assets/29059640/f7a7a0e9-98b9-4976-afce-fe4916cdd209)

**Comment by sha237gh** [comment]
+1, having the same problem. is there any way around this?

**Comment by georgezikos** [comment]
@sha237gh I just had it ignore the peer dependencies and install anyway using `npm install embla-carousel-wheel-gestures --save --legacy-peer-deps` and it seems to work just fine.

**Comment by coreybrendan** [comment]
Hey, gang! I'm also experiencing this conflict when attempting an npm install (on the latest version of Embla). Wondering if there's a fix queued for this issue? My team is wary of introducing a `--legacy-peer-deps` into prod.

**Comment by hellomkreyes** [comment]
Experiencing the same problem as well! I want to implement the plugin in a production codebase, so I kinda want to avoid having to use the `--legacy-peer-deps` workaround.

**Comment by davidjerleke** [comment]
Hi @hellomkreyes, @coreybrendan, @me-0xe, @georgezikos, @sha237gh.

I think we need to add a tilde (~) sign before the package version [here](https://github.com/xiel/embla-carousel-wheel-gestures/blob/master/embla-carousel-wheel-gestures/package.json#L61) to avoid this happening every time a new minor version of `embla-carousel` is released.

Feel free to open a PR for this.

Best,
David

**Comment by xiel** [comment]
Sorry had busy weeks, should be [fixed](https://github.com/xiel/embla-carousel-wheel-gestures/commit/b01924249ab1aa0fc8cddd5d7e9932cb9c26074b#diff-fe1e8f78ac1778762771f91cf891ffaa3522ff36c3a8c7502b4b4079254aef58L52-R52) now. I was not aware the tilde would work for prereleases. 🙏

Please try again with [embla-carousel-wheel-gestures@8.0.0-rc05](https://www.npmjs.com/package/embla-carousel-wheel-gestures/v/8.0.0-rc05) 📦
I tested it with yarn and npm (9.5.1) and it worked like that.

Cheers and thanks for your patience.

**Comment by me-0xe** [comment]
Thanks for the response. Appreciate the effort that goes into Embla and the plugins!
