### ISSUE TITLE
"rtl" direction doesn't work with the images when given loading lazy property 

### ISSUE THREAD

**Issue by OmarShref** [xiel/embla-carousel-wheel-gestures#192]
"rtl" direction doesn't work with the images when given loading lazy property because the carousel  doesn't consider the image entered the view port from the right direction but from the left direction

**Comment by davidjerleke** [comment]
@OmarShref you didn’t share much details about your setup but if you’re using v8.0.0-rc01 and up it’s unlikely that it’s behaving the way you describe. This is because Embla is using `IntersectionObserver` under the hood which is a native browser API.

Best,
David

**Comment by davidjerleke** [comment]
Tracked here:

- https://github.com/davidjerleke/embla-carousel/discussions/736

Closing this.
