### ISSUE TITLE
Disable Scroll indication?

### ISSUE THREAD

**Issue by felixmpaulus** [xiel/embla-carousel-wheel-gestures#193]
Since enabling this plugin, most of the times when I hover over a carousel, it indicates its scrollability by quickly dragging itself to one side and then jumping back to its default position.

I think is is done to signal to the user that a horizontal scroll is possible.
This happens without any user interaction and it is not consistent. 

Is there a way to disable this?

**Comment by xiel** [comment]
Unlikely, as we don't do anything on hover

**Comment by felixmpaulus** [comment]
Thanks for the swift reply. Must be caused by something else then.
