### ISSUE TITLE
Disable wheel gestures when scroll next and previous are both false

### ISSUE THREAD

**Issue by hamidrezahanafi** [xiel/embla-carousel-wheel-gestures#198]
Hello there and thanks for this great plugin!

Is there any way to disable wheel gestures when there are not enough slides to scroll? Right now when `emblaApi.canScrollPrev()` and `emblaApi.canScrollNext()` are false, I can still drag slides with wheel gestures and it snaps back into the place. 

Best,

**Comment by xiel** [comment]
You would need to not pass the plugin in the plugins array in case u have less items.

**Comment by hamidrezahanafi** [comment]
Thanks for the reply. Do you have any responsive solution for this?
This is going to change the ref when screen size changes, destroy and carousel, reinit it and defy the use of breakpoints.
