### ISSUE TITLE
Test with RTL

### ISSUE THREAD

**Issue by davidcetinkaya** [xiel/embla-carousel-wheel-gestures#55]
Hello Felix (@xiel),

I just released RTL support for Embla Carousel ([See release here](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.1.0)), and I think we need to test if the wheel gestures work with it. I’m hoping that it’ll work out of the box but we should make sure it does. I have a lot of feature requests to work on right now so if you have any time to test it before I do, please test this 🙂.

Best,
David

**Comment by xiel** [comment]
Hey David (@davidcetinkaya),

thanks for the heads up, sure, I will check and update if needed ;)

Best,
Felix

**Comment by davidcetinkaya** [comment]
Thanks a bunch Felix (@xiel)!

**Comment by xiel** [comment]
A small update was needed, you can check it out here:
https://embla-carousel-wheel-gestures-git-feature-55-rtl.xiel.vercel.app/?rtl

**Comment by davidcetinkaya** [comment]
Hello Felix (@xiel),
I just tested the link you provided [here](https://github.com/xiel/embla-carousel-wheel-gestures/issues/55#issuecomment-725667765) and it seems to be working as expected.

Nice work 🥳!
